---
az-configuration:
- name: europe-west1-b
- name: europe-west1-c
- name: europe-west1-d
network-assignment:
  network:
    name: infrastructure
  singleton_availability_zone:
    name: europe-west1-b
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: infrastructure
    subnets:
    - iaas_identifier: vpc-pas-2-0-admin/admin-infrastructure-subnet/europe-west1
      cidr: 10.0.0.0/26
      dns: 169.254.169.254
      gateway: 10.0.0.1
      reserved_ip_ranges: 10.0.0.1-10.0.0.9
      availability_zone_names:
      - europe-west1-b
      - europe-west1-c
      - europe-west1-d
  - name: pks
    subnets:
    - iaas_identifier: vpc-pas-2-0-admin/pks/europe-west1
      cidr: 10.0.10.0/24
      dns: 169.254.169.254
      gateway: 10.0.10.1
      reserved_ip_ranges: 10.0.10.1-10.0.10.9
      availability_zone_names:
      - europe-west1-b
      - europe-west1-c
      - europe-west1-d
  - name: pks-services
    subnets:
    - iaas_identifier: vpc-pas-2-0-admin/pks-services/europe-west1
      cidr: 10.0.11.0/24
      dns: 169.254.169.254
      gateway: 10.0.11.1
      reserved_ip_ranges: 10.0.11.1-10.0.11.9
      availability_zone_names:
      - europe-west1-b
      - europe-west1-c
      - europe-west1-d
properties-configuration:
  director_configuration:
    ntp_servers_string: metadata.google.internal
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: true
  iaas_configuration:
    project: ((gcp-project-id))
    default_deployment_tag: pks-om-dep-tag
    auth_json: ((gcp-credentials))
resource-configuration:
  compilation:
    instances: 8
