---
opsman-configuration:
  gcp:
    gcp_service_account: ((gcp-credentials))
    project: ((gcp-project-id))
    region: europe-west1
    zone: europe-west1-c
    vm_name: opsmanager-vm
    vpc_subnet: admin-infrastructure
    tags: ops-manager-external
    custom_cpu: 2
    custom_memory: 8
    boot_disk_size: 200
    public_ip: ((opsman-public-ip))
    private_ip: 10.0.0.2
